/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        this.setSize(971,562);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Header = new javax.swing.JLabel();
        Header1 = new javax.swing.JLabel();
        addNewEmployee = new javax.swing.JButton();
        updateEmployee = new javax.swing.JButton();
        searchEmployee = new javax.swing.JButton();
        removeEmployee = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee_Payroll");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(181, 25));
        setMinimumSize(new java.awt.Dimension(181, 25));
        getContentPane().setLayout(null);

        Header.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Header.setText("Employee Payroll");
        Header.setName(""); // NOI18N
        getContentPane().add(Header);
        Header.setBounds(290, 20, 410, 70);

        Header1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Header1.setText("Main Menu");
        getContentPane().add(Header1);
        Header1.setBounds(430, 150, 100, 22);

        addNewEmployee.setBackground(new java.awt.Color(204, 204, 204));
        addNewEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addNewEmployee.setText("Add a new employee ");
        addNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(addNewEmployee);
        addNewEmployee.setBounds(90, 240, 260, 40);

        updateEmployee.setBackground(new java.awt.Color(204, 204, 204));
        updateEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        updateEmployee.setText("Update an existing employee");
        updateEmployee.setMaximumSize(new java.awt.Dimension(181, 25));
        updateEmployee.setMinimumSize(new java.awt.Dimension(181, 25));
        updateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(updateEmployee);
        updateEmployee.setBounds(560, 240, 250, 40);

        searchEmployee.setBackground(new java.awt.Color(204, 204, 204));
        searchEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchEmployee.setText("Search an existing employee");
        searchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(searchEmployee);
        searchEmployee.setBounds(90, 330, 260, 40);

        removeEmployee.setBackground(new java.awt.Color(204, 204, 204));
        removeEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        removeEmployee.setText("Remove an existing employee");
        removeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(removeEmployee);
        removeEmployee.setBounds(559, 330, 250, 40);

        exit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(440, 450, 80, 33);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void addNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        new addEmployee().setVisible(true);
       // this.dispose();
    }                                              

    private void updateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        new updateEmployee().setVisible(true);
      //  this.dispose();
    }                                              

    private void searchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        new searchEmployee().setVisible(true);
       // this.dispose();
    }                                              

    private void removeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        new removeEmployee().setVisible(true);
        //this.dispose();
    }                                              

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        this.dispose();
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Header1;
    private javax.swing.JButton addNewEmployee;
    private javax.swing.JButton exit;
    private javax.swing.JButton removeEmployee;
    private javax.swing.JButton searchEmployee;
    private javax.swing.JButton updateEmployee;
    // End of variables declaration                   
}
public class addEmployee extends javax.swing.JFrame {

    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
        this.setSize(1061,631);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        header = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        ename = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        designation = new javax.swing.JLabel();
        basic = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        empName = new javax.swing.JTextField();
        empDob = new javax.swing.JTextField();
        empDesign = new javax.swing.JTextField();
        empBasic = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText(" Add new Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 429, 85));

        eid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        eid.setText("Employee ID ");
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        ename.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        ename.setText("Employee Name");
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, -1));

        dob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dob.setText("Date of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        sex.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        sex.setText("Gender");
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        designation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        designation.setText("Designation");
        getContentPane().add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, -1));

        basic.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        basic.setText("Basic Pay");
        getContentPane().add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        instruction.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        instruction.setText("Enter the details of the employee");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 300, -1));
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 350, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 350, -1));
        getContentPane().add(empDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 350, -1));
        getContentPane().add(empDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 350, -1));
        getContentPane().add(empBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 350, -1));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 340, -1));

        add.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 150, 50));

        cancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 355, 140, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
    }                                       

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        this.dispose();
    }                                      

    private void addActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        String eid,ename,gender,designation,dob;
        Double basic;
        eid = empID.getText().trim();
        ename = empName.getText().trim();
        gender = genderbox.getSelectedItem().toString();
        designation = empDesign.getText().trim();
        dob = empDob.getText().trim();
        try{
            basic = Double.parseDouble(empBasic.getText().trim());
            if(eid.isEmpty()||ename.isEmpty()||gender.isEmpty()||designation.isEmpty()||dob.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Fill all the details to proceed!");
            }
            else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
                    String query = "Insert into Emp_Payroll (eid, ename, dob, sex, designation, basic) values('"+eid+"','"+ename+"','"+dob+"','"+gender+"','"+designation+"','"+basic+"')";
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    query = "call net_pay('"+eid+"','"+basic+"')";
                    ps = con.prepareStatement(query);
                    rs = ps.executeQuery();
                    JOptionPane.showMessageDialog(this, "Employee added Succesfully!");
                    this.dispose();
                }
                catch(SQLException se)
                {
                    Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "DataBase error Insertion failed!");
                }
            }               
        }
        catch(NumberFormatException Ne)
        {
            JOptionPane.showMessageDialog(this, "Insert correct double value in basic pay!");
        }        
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JLabel basic;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel designation;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel eid;
    private javax.swing.JTextField empBasic;
    private javax.swing.JTextField empDesign;
    private javax.swing.JTextField empDob;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JLabel ename;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel header;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel sex;
    // End of variables declaration                   
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class addEmployee extends javax.swing.JFrame {

    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
        this.setSize(1061,631);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        header = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        ename = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        designation = new javax.swing.JLabel();
        basic = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        empName = new javax.swing.JTextField();
        empDob = new javax.swing.JTextField();
        empDesign = new javax.swing.JTextField();
        empBasic = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText(" Add new Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 429, 85));

        eid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        eid.setText("Employee ID ");
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        ename.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        ename.setText("Employee Name");
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, -1));

        dob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dob.setText("Date of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        sex.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        sex.setText("Gender");
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        designation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        designation.setText("Designation");
        getContentPane().add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, -1));

        basic.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        basic.setText("Basic Pay");
        getContentPane().add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        instruction.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        instruction.setText("Enter the details of the employee");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 300, -1));
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 350, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 350, -1));
        getContentPane().add(empDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 350, -1));
        getContentPane().add(empDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 350, -1));
        getContentPane().add(empBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 350, -1));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 340, -1));

        add.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 150, 50));

        cancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 355, 140, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
    }                                       

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        this.dispose();
    }                                      

    private void addActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        String eid,ename,gender,designation,dob;
        Double basic;
        eid = empID.getText().trim();
        ename = empName.getText().trim();
        gender = genderbox.getSelectedItem().toString();
        designation = empDesign.getText().trim();
        dob = empDob.getText().trim();
        try{
            basic = Double.parseDouble(empBasic.getText().trim());
            if(eid.isEmpty()||ename.isEmpty()||gender.isEmpty()||designation.isEmpty()||dob.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Fill all the details to proceed!");
            }
            else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
                    String query = "Insert into Emp_Payroll (eid, ename, dob, sex, designation, basic) values('"+eid+"','"+ename+"','"+dob+"','"+gender+"','"+designation+"','"+basic+"')";
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    query = "call net_pay('"+eid+"','"+basic+"')";
                    ps = con.prepareStatement(query);
                    rs = ps.executeQuery();
                    JOptionPane.showMessageDialog(this, "Employee added Succesfully!");
                    this.dispose();
                }
                catch(SQLException se)
                {
                    Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "DataBase error Insertion failed!");
                }
            }               
        }
        catch(NumberFormatException Ne)
        {
            JOptionPane.showMessageDialog(this, "Insert correct double value in basic pay!");
        }        
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JLabel basic;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel designation;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel eid;
    private javax.swing.JTextField empBasic;
    private javax.swing.JTextField empDesign;
    private javax.swing.JTextField empDob;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JLabel ename;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel header;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel sex;
    // End of variables declaration                   
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class updateEmployee extends javax.swing.JFrame {

    /**
     * Creates new form updateEmployee
     */
    public updateEmployee() {
        initComponents();
        this.setSize(1000,715);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        header = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        design = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        empName = new javax.swing.JTextField();
        empDob = new javax.swing.JTextField();
        empDesign = new javax.swing.JTextField();
        empBasic = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        genderbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update an Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText("Update an Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        instruction.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instruction.setText("Enter the following details to update an employee");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        id.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        id.setText("Employee ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, -1));

        name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        name.setText("Employee Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        dob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dob.setText("Data of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        gender.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        design.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        design.setText("Designation");
        getContentPane().add(design, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        pay.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        pay.setText("Basic Pay");
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 320, -1));
        getContentPane().add(empDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 320, -1));

        empDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDesignActionPerformed(evt);
            }
        });
        getContentPane().add(empDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 320, -1));

        empBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBasicActionPerformed(evt);
            }
        });
        getContentPane().add(empBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 320, -1));

        update.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 110, 50));

        exit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        exit.setText("Cancel");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 110, 40));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female", " " }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 320, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void empDesignActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void empBasicActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String eid,ename,gender,designation,dob;
        Double basic;
        eid = empID.getText().trim();
        ename = empName.getText().trim();
        gender = genderbox.getSelectedItem().toString();
        designation = empDesign.getText().trim();
        dob = empDob.getText().trim();
        try{
            basic = Double.parseDouble(empBasic.getText().trim());
            if(eid.isEmpty()||ename.isEmpty()||gender.isEmpty()||designation.isEmpty()||dob.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Fill all the details to proceed!");
            }
            else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
                    String query = "select * from Emp_Payroll where eid ='"+eid+"'";
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    if(rs.next())
                    {
                        query = "Update Emp_Payroll set ename = '"+ename+"', dob = '"+dob+"', sex = '"+gender+"', designation = '"+designation+"', basic = '"+basic+"' where eid = '"+eid+"'";
                        ps = con.prepareStatement(query);
                        ps.executeQuery();
                        query = "call net_pay('"+eid+"','"+basic+"')";
                        ps = con.prepareStatement(query);
                        rs = ps.executeQuery();
                        JOptionPane.showMessageDialog(this, "Employee Upddated Succesfully!");
                        this.dispose();
                }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "There is no such employees in the database!");
                    }
                }    
                catch(SQLException se)
                {
                    Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "DataBase error Updation failed!");
                }
            }               
        }
        catch(NumberFormatException Ne)
        {
            JOptionPane.showMessageDialog(this, "Insert correct double value in basic pay!");
        }                                 

    }                                      

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        this.dispose();
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel design;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField empBasic;
    private javax.swing.JTextField empDesign;
    private javax.swing.JTextField empDob;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel header;
    private javax.swing.JLabel id;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pay;
    private javax.swing.JButton update;
    // End of variables declaration                   
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class searchEmployee extends javax.swing.JFrame {

    /**
     * Creates new form searchEmployee
     */
    public searchEmployee() {
        initComponents();
        this.setSize(973,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        id = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        empDob = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        design = new javax.swing.JLabel();
        empDesign = new javax.swing.JTextField();
        pay = new javax.swing.JLabel();
        empBasic = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        header = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        getEmp = new javax.swing.JTextField();
        empGender = new javax.swing.JTextField();
        view = new javax.swing.JButton();
        npay = new javax.swing.JLabel();
        netpay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        id.setText("Employee ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, -1));
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));

        name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        name.setText("Employee Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 320, -1));

        dob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dob.setText("Data of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        getContentPane().add(empDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 320, -1));

        gender.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        design.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        design.setText("Designation");
        getContentPane().add(design, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        empDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDesignActionPerformed(evt);
            }
        });
        getContentPane().add(empDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 320, -1));

        pay.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        pay.setText("Basic Pay");
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        empBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBasicActionPerformed(evt);
            }
        });
        getContentPane().add(empBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 320, -1));

        search.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText("Search an Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        instruction.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instruction.setText("Enter the Employee Id");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        getContentPane().add(getEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 250, -1));
        getContentPane().add(empGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 320, -1));

        view.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        view.setText("Table view");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, -1, -1));

        npay.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        npay.setText("Net Pay");
        getContentPane().add(npay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));
        getContentPane().add(netpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 320, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void empDesignActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void empBasicActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String eid;
        eid = getEmp.getText().trim();
        if(eid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter the value of the employee to search!");
        }
        else{
            try{
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
            String query = "Select * from Emp_Payroll where eid = '"+eid+"'";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Employee found!");
                empID.setText(rs.getString("eid"));
                empName.setText(rs.getString("ename"));
                empGender.setText(rs.getString("sex"));
                empDesign.setText(rs.getString("designation"));
                empDob.setText(rs.getString("dob").substring(0,10));
                empBasic.setText(rs.getString("basic"));
                netpay.setText(rs.getString("net_pay"));
            }
            else
            {
                JOptionPane.showMessageDialog(this," No Employees found!");
            }
        }
            catch(SQLException se)
            {
                 Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                 JOptionPane.showMessageDialog(this, "DataBase error Search failed!");
            }
    }                                      
    }
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        String eid;
        eid = getEmp.getText().trim();
        new tableview(eid).setVisible(true);
        this.dispose();
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel design;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField empBasic;
    private javax.swing.JTextField empDesign;
    private javax.swing.JTextField empDob;
    private javax.swing.JTextField empGender;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField getEmp;
    private javax.swing.JLabel header;
    private javax.swing.JLabel id;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel name;
    private javax.swing.JTextField netpay;
    private javax.swing.JLabel npay;
    private javax.swing.JLabel pay;
    private javax.swing.JButton search;
    private javax.swing.JButton view;
    // End of variables declaration                   
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class removeEmployee extends javax.swing.JFrame {

    /**
     * Creates new form removeEmployee
     */
    public removeEmployee() {
        initComponents();
        this.setSize(799,455);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        header = new javax.swing.JLabel();
        rem = new javax.swing.JLabel();
        EmpId = new javax.swing.JTextField();
        Remove = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText("Remove an Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        rem.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        rem.setText("Enter the Employee id");
        getContentPane().add(rem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(EmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 330, 30));

        Remove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 130, 50));

        cancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 130, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        this.dispose();
    }                                      

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String eid;
        eid = EmpId.getText().trim();
        if(eid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter the value of the employee to search!");
        }
        else{
            try{
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
            String query = "Select * from Emp_Payroll where eid = '"+eid+"'";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Employee found!");
                query = "Delete from Emp_Payroll where eid ='"+eid+"'";
                ps = con.prepareStatement(query);
                ps.executeQuery();
                JOptionPane.showMessageDialog(this, "Employee removed successfully!");
                this.dispose();
                
            }
            else
            {
                JOptionPane.showMessageDialog(this," No Employees found!");
            }
        }
            catch(SQLException se)
            {
                 Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                 JOptionPane.showMessageDialog(this, "DataBase error Remove failed!");
            }
    }                                      
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField EmpId;
    private javax.swing.JButton Remove;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel rem;
    // End of variables declaration                   
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class tableview extends javax.swing.JFrame {

    /**
     * Creates new form tableview
     */
    public tableview()
    {
        initComponents();
        this.setSize(1350,558);
    }
    public tableview(String eid) {   
        initComponents();
        tableDetails(eid);
    }
    public void tableDetails(String eid) {
        try{
        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
        String query = "Select * from Emp_Payroll where eid = '"+eid+"'";
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        DefaultTableModel model =(DefaultTableModel)empTable.getModel();
        model.setRowCount(0);
        if(rs.next())
        {
           model.addRow(new Object[]{rs.getString("eid"),rs.getString("ename"),rs.getString("dob").substring(0,10),
                   rs.getString("sex"),rs.getString("designation"),rs.getString("basic"),rs.getString("da"),
           rs.getString("hra"),rs.getString("pf"),rs.getString("mc"),rs.getString("gross"),
           rs.getString("tot_deduc"),rs.getString("net_pay")});
        }
        else{
            JOptionPane.showMessageDialog(this,"No employee found");
        }
      }
        catch(SQLException se)
        {
            Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
            JOptionPane.showMessageDialog(this, "DataBase error Search failed!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        header = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Table view for Search");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText("Table view of records");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        empTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Date of Birth", "Sex", "Designation", "Basic Pay", "DA", "HRA", "PF", "MC", "Gross Pay", "Total detuction", "Net Pay"
            }
        ));
        jScrollPane1.setViewportView(empTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1330, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable empTable;
    private javax.swing.JLabel header;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}

