INSERT INTO Countries  VALUES('Afghanistan');  
INSERT INTO Countries  VALUES('Albania');  
INSERT INTO Countries  VALUES('Algeria');  
INSERT INTO Countries  VALUES('Andorra');  
INSERT INTO Countries  VALUES('Angola');  
INSERT INTO Countries  VALUES('Anguilla');  
INSERT INTO Countries  VALUES('Antigua & Barbuda');  
INSERT INTO Countries  VALUES('Argentina');  
INSERT INTO Countries  VALUES('Armenia');  
INSERT INTO Countries  VALUES('Australia');  
INSERT INTO Countries  VALUES('Austria');  
INSERT INTO Countries  VALUES('Azerbaijan');  
INSERT INTO Countries  VALUES('Bahamas');  
INSERT INTO Countries  VALUES('Bahrain');  
INSERT INTO Countries  VALUES('Bangladesh');  
INSERT INTO Countries  VALUES('Barbados');  
INSERT INTO Countries  VALUES('Belarus');  
INSERT INTO Countries  VALUES('Belgium');  
INSERT INTO Countries  VALUES('Belize');  
INSERT INTO Countries  VALUES('Benin');  
INSERT INTO Countries  VALUES('Bermuda');  
INSERT INTO Countries  VALUES('Bhutan');  
INSERT INTO Countries  VALUES('Bolivia');  
INSERT INTO Countries  VALUES('Bosnia & Herzegovina');  
INSERT INTO Countries  VALUES('Botswana');  
INSERT INTO Countries  VALUES('Brazil');  
INSERT INTO Countries  VALUES('Brunei Darussalam');  
INSERT INTO Countries  VALUES('Bulgaria');  
INSERT INTO Countries  VALUES('Burkina Faso');  
INSERT INTO Countries  VALUES('Myanmar/Burma');  
INSERT INTO Countries  VALUES('Burundi');  
INSERT INTO Countries  VALUES('Cambodia');  
INSERT INTO Countries  VALUES('Cameroon');  
INSERT INTO Countries  VALUES('Canada');  
INSERT INTO Countries  VALUES('Cape Verde');  
INSERT INTO Countries  VALUES('Cayman Islands');  
INSERT INTO Countries  VALUES('Central African Republic');  
INSERT INTO Countries  VALUES('Chad');  
INSERT INTO Countries  VALUES('Chile');  
INSERT INTO Countries  VALUES('China');  
INSERT INTO Countries  VALUES('Colombia');  
INSERT INTO Countries  VALUES('Comoros');  
INSERT INTO Countries  VALUES('Congo');  
INSERT INTO Countries  VALUES('Costa Rica');  
INSERT INTO Countries  VALUES('Croatia');  
INSERT INTO Countries  VALUES('Cuba');  
INSERT INTO Countries  VALUES('Cyprus');  
INSERT INTO Countries  VALUES('Czech Republic');  
INSERT INTO Countries  VALUES('Democratic Republic of the Congo');  
INSERT INTO Countries  VALUES('Denmark');  
INSERT INTO Countries  VALUES('Djibouti');  
INSERT INTO Countries  VALUES('Dominican Republic');  
INSERT INTO Countries  VALUES('Dominica');  
INSERT INTO Countries  VALUES('Ecuador');  
INSERT INTO Countries  VALUES('Egypt');  
INSERT INTO Countries  VALUES('El Salvador');  
INSERT INTO Countries  VALUES('Equatorial Guinea');  
INSERT INTO Countries  VALUES('Eritrea');  
INSERT INTO Countries  VALUES('Estonia');  
INSERT INTO Countries  VALUES('Ethiopia');  
INSERT INTO Countries  VALUES('Fiji');  
INSERT INTO Countries  VALUES('Finland');  
INSERT INTO Countries  VALUES('France');  
INSERT INTO Countries  VALUES('French Guiana');  
INSERT INTO Countries  VALUES('Gabon');  
INSERT INTO Countries  VALUES('Gambia');  
INSERT INTO Countries  VALUES('Georgia');  
INSERT INTO Countries  VALUES('Germany');  
INSERT INTO Countries  VALUES('Ghana');  
INSERT INTO Countries  VALUES('Great Britain');  
INSERT INTO Countries  VALUES('Greece');  
INSERT INTO Countries  VALUES('Grenada');  
INSERT INTO Countries  VALUES('Guadeloupe');  
INSERT INTO Countries  VALUES('Guatemala');  
INSERT INTO Countries  VALUES('Guinea');  
INSERT INTO Countries  VALUES('Guinea-Bissau');  
INSERT INTO Countries  VALUES('Guyana');  
INSERT INTO Countries  VALUES('Haiti');  
INSERT INTO Countries  VALUES('Honduras');  
INSERT INTO Countries  VALUES('Hungary');  
INSERT INTO Countries  VALUES('Iceland');  
INSERT INTO Countries  VALUES('India');  
INSERT INTO Countries  VALUES('Indonesia');  
INSERT INTO Countries  VALUES('Iran');  
INSERT INTO Countries  VALUES('Iraq');  
INSERT INTO Countries  VALUES('Israel and the Occupied Territories');  
INSERT INTO Countries  VALUES('Italy');  
INSERT INTO Countries  VALUES('Ivory Coast (Cote d''Ivoire)');  
INSERT INTO Countries  VALUES('Jamaica');  
INSERT INTO Countries  VALUES('Japan');  
INSERT INTO Countries  VALUES('Jordan');  
INSERT INTO Countries  VALUES('Kazakhstan');  
INSERT INTO Countries  VALUES('Kenya');  
INSERT INTO Countries  VALUES('Kosovo');  
INSERT INTO Countries  VALUES('Kuwait');  
INSERT INTO Countries  VALUES('Kyrgyz Republic (Kyrgyzstan)');  
INSERT INTO Countries  VALUES('Laos');  
INSERT INTO Countries  VALUES('Latvia');  
INSERT INTO Countries  VALUES('Lebanon');  
INSERT INTO Countries  VALUES('Lesotho');  
INSERT INTO Countries  VALUES('Liberia');  
INSERT INTO Countries  VALUES('Libya');  
INSERT INTO Countries  VALUES('Liechtenstein');  
INSERT INTO Countries  VALUES('Lithuania');  
INSERT INTO Countries  VALUES('Luxembourg');  
INSERT INTO Countries  VALUES('Republic of Macedonia');  
INSERT INTO Countries  VALUES('Madagascar');  
INSERT INTO Countries  VALUES('Malawi');  
INSERT INTO Countries  VALUES('Malaysia');  
INSERT INTO Countries  VALUES('Maldives');  
INSERT INTO Countries  VALUES('Mali');  
INSERT INTO Countries  VALUES('Malta');  
INSERT INTO Countries  VALUES('Martinique');  
INSERT INTO Countries  VALUES('Mauritania');  
INSERT INTO Countries  VALUES('Mauritius');  
INSERT INTO Countries  VALUES('Mayotte');  
INSERT INTO Countries  VALUES('Mexico');  
INSERT INTO Countries  VALUES('Moldova, Republic of');  
INSERT INTO Countries  VALUES('Monaco');  
INSERT INTO Countries  VALUES('Mongolia');  
INSERT INTO Countries  VALUES('Montenegro');  
INSERT INTO Countries  VALUES('Montserrat');  
INSERT INTO Countries  VALUES('Morocco');  
INSERT INTO Countries  VALUES('Mozambique');  
INSERT INTO Countries  VALUES('Namibia');  
INSERT INTO Countries  VALUES('Nepal');  
INSERT INTO Countries  VALUES('Netherlands');  
INSERT INTO Countries  VALUES('New Zealand');  
INSERT INTO Countries  VALUES('Nicaragua');  
INSERT INTO Countries  VALUES('Niger');  
INSERT INTO Countries  VALUES('Nigeria');  
INSERT INTO Countries  VALUES('Korea, Democratic Republic of (North Korea)');  
INSERT INTO Countries  VALUES('Norway');  
INSERT INTO Countries  VALUES('Oman');  
INSERT INTO Countries  VALUES('Pacific Islands');  
INSERT INTO Countries  VALUES('Pakistan');  
INSERT INTO Countries  VALUES('Panama');  
INSERT INTO Countries  VALUES('Papua New Guinea');  
INSERT INTO Countries  VALUES('Paraguay');  
INSERT INTO Countries  VALUES('Peru');  
INSERT INTO Countries  VALUES('Philippines');  
INSERT INTO Countries  VALUES('Poland');  
INSERT INTO Countries  VALUES('Portugal');  
INSERT INTO Countries  VALUES('Puerto Rico');  
INSERT INTO Countries  VALUES('Qatar');  
INSERT INTO Countries  VALUES('Reunion');  
INSERT INTO Countries  VALUES('Romania');  
INSERT INTO Countries  VALUES('Russian Federation');  
INSERT INTO Countries  VALUES('Rwanda');  
INSERT INTO Countries  VALUES('Saint Kitts and Nevis');  
INSERT INTO Countries  VALUES('Saint Lucia');  
INSERT INTO Countries  VALUES('Saint Vincent''s & Grenadines');  
INSERT INTO Countries  VALUES('Samoa');  
INSERT INTO Countries  VALUES('Sao Tome and Principe');  
INSERT INTO Countries  VALUES('Saudi Arabia');  
INSERT INTO Countries  VALUES('Senegal');  
INSERT INTO Countries  VALUES('Serbia');  
INSERT INTO Countries  VALUES('Seychelles');  
INSERT INTO Countries  VALUES('Sierra Leone');  
INSERT INTO Countries  VALUES('Singapore');  
INSERT INTO Countries  VALUES('Slovak Republic (Slovakia)');  
INSERT INTO Countries  VALUES('Slovenia');  
INSERT INTO Countries  VALUES('Solomon Islands');  
INSERT INTO Countries  VALUES('Somalia');  
INSERT INTO Countries  VALUES('South Africa');  
INSERT INTO Countries  VALUES('Korea, Republic of (South Korea)');  
INSERT INTO Countries  VALUES('South Sudan');  
INSERT INTO Countries  VALUES('Spain');  
INSERT INTO Countries  VALUES('Sri Lanka');  
INSERT INTO Countries  VALUES('Sudan');  
INSERT INTO Countries  VALUES('Suriname');  
INSERT INTO Countries  VALUES('Swaziland');  
INSERT INTO Countries  VALUES('Sweden');  
INSERT INTO Countries  VALUES('Switzerland');  
INSERT INTO Countries  VALUES('Syria');  
INSERT INTO Countries  VALUES('Tajikistan');  
INSERT INTO Countries  VALUES('Tanzania');  
INSERT INTO Countries  VALUES('Thailand');  
INSERT INTO Countries  VALUES('Timor Leste');  
INSERT INTO Countries  VALUES('Togo');  
INSERT INTO Countries  VALUES('Trinidad & Tobago');  
INSERT INTO Countries  VALUES('Tunisia');  
INSERT INTO Countries  VALUES('Turkey');  
INSERT INTO Countries  VALUES('Turkmenistan');  
INSERT INTO Countries  VALUES('Turks & Caicos Islands');  
INSERT INTO Countries  VALUES('Uganda');  
INSERT INTO Countries  VALUES('Ukraine');  
INSERT INTO Countries  VALUES('United Arab Emirates');  
INSERT INTO Countries  VALUES('United States of America (USA)');  
INSERT INTO Countries  VALUES('Uruguay');  
INSERT INTO Countries  VALUES('Uzbekistan');  
INSERT INTO Countries  VALUES('Venezuela');  
INSERT INTO Countries  VALUES('Vietnam');  
INSERT INTO Countries  VALUES('Virgin Islands (UK)');  
INSERT INTO Countries  VALUES('Virgin Islands (US)');  
INSERT INTO Countries  VALUES('Yemen');  
INSERT INTO Countries  VALUES('Zambia');  
INSERT INTO Countries  VALUES('Zimbabwe'); 