/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class addEmployee extends javax.swing.JFrame {

    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
        this.setSize(980,585);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        ename = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        designation = new javax.swing.JLabel();
        basic = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        empName = new javax.swing.JTextField();
        empDob = new javax.swing.JTextField();
        empDesign = new javax.swing.JTextField();
        empBasic = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText(" Add new Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 429, 85));

        eid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        eid.setText("Employee ID ");
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        ename.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        ename.setText("Employee Name");
        getContentPane().add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, -1));

        dob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dob.setText("Date of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        sex.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        sex.setText("Gender");
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        designation.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        designation.setText("Designation");
        getContentPane().add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, -1));

        basic.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        basic.setText("Basic Pay");
        getContentPane().add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        instruction.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        instruction.setText("Enter the details of the employee");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 300, -1));
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 350, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 350, -1));
        getContentPane().add(empDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 350, -1));
        getContentPane().add(empDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 350, -1));
        getContentPane().add(empBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 350, -1));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 340, -1));

        add.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 150, 50));

        cancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 355, 140, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empNameActionPerformed

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderboxActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String eid,ename,gender,designation,dob;
        Double basic;
        eid = empID.getText().trim();
        ename = empName.getText().trim();
        gender = genderbox.getSelectedItem().toString();
        designation = empDesign.getText().trim();
        dob = empDob.getText().trim();
        try{
            basic = Double.parseDouble(empBasic.getText().trim());
            if(eid.isEmpty()||ename.isEmpty()||gender.isEmpty()||designation.isEmpty()||dob.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Fill all the details to proceed!");
            }
            else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
                    String query = "Insert into Emp_Payroll (eid, ename, dob, sex, designation, basic) values('"+eid+"','"+ename+"','"+dob+"','"+gender+"','"+designation+"','"+basic+"')";
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    query = "call net_pay('"+eid+"','"+basic+"')";
                    ps = con.prepareStatement(query);
                    rs = ps.executeQuery();
                    JOptionPane.showMessageDialog(this, "Employee added Succesfully!");
                }
                catch(SQLException se)
                {
                    Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "DataBase error Insertion failed!");
                }
            }               
        }
        catch(NumberFormatException Ne)
        {
            JOptionPane.showMessageDialog(this, "Insert correct double value in basic pay!");
        }        
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel basic;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel designation;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel eid;
    private javax.swing.JTextField empBasic;
    private javax.swing.JTextField empDesign;
    private javax.swing.JTextField empDob;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JLabel ename;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel header;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel sex;
    // End of variables declaration//GEN-END:variables
}
