/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sreed
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class updateEmployee extends javax.swing.JFrame {

    /**
     * Creates new form updateEmployee
     */
    public updateEmployee() {
        initComponents();
        this.setSize(1000,715);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        design = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        empName = new javax.swing.JTextField();
        empDob = new javax.swing.JTextField();
        empDesign = new javax.swing.JTextField();
        empBasic = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        genderbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update an Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        header.setText("Update an Employee");
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        instruction.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instruction.setText("Enter the following details to update an employee");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        id.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        id.setText("Employee ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, -1));

        name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        name.setText("Employee Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        dob.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        dob.setText("Data of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        gender.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        design.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        design.setText("Designation");
        getContentPane().add(design, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        pay.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        pay.setText("Basic Pay");
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));
        getContentPane().add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        getContentPane().add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 320, -1));
        getContentPane().add(empDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 320, -1));

        empDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDesignActionPerformed(evt);
            }
        });
        getContentPane().add(empDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 320, -1));

        empBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBasicActionPerformed(evt);
            }
        });
        getContentPane().add(empBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 320, -1));

        update.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 110, 50));

        exit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        exit.setText("Cancel");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 110, 40));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female", " " }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        getContentPane().add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 320, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderboxActionPerformed

    private void empDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDesignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empDesignActionPerformed

    private void empBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBasicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empBasicActionPerformed

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String eid,ename,gender,designation,dob;
        Double basic;
        eid = empID.getText().trim();
        ename = empName.getText().trim();
        gender = genderbox.getSelectedItem().toString();
        designation = empDesign.getText().trim();
        dob = empDob.getText().trim();
        try{
            basic = Double.parseDouble(empBasic.getText().trim());
            if(eid.isEmpty()||ename.isEmpty()||gender.isEmpty()||designation.isEmpty()||dob.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Fill all the details to proceed!");
            }
            else{
                try{
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "HR", "1234");
                    String query = "select * from Emp_Table where eid ='"+eid+"'";
                    PreparedStatement ps = con.prepareStatement(query);
                    ResultSet rs = ps.executeQuery();
                    if(rs.next())
                    {
                        query = "Update Emp_Payroll set ename = '"+ename+"', dob = '"+dob+"', sex = '"+gender+"', designation = '"+designation+"', basic = '"+basic+"' where eid = '"+eid+"'";
                        ps = con.prepareStatement(query);
                        ps.executeQuery();
                        query = "call net_pay('"+eid+"','"+basic+"')";
                        ps = con.prepareStatement(query);
                        rs = ps.executeQuery();
                        JOptionPane.showMessageDialog(this, "Employee Upddated Succesfully!");
                }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "There is no such employees in the database!");
                    }
                }    
                catch(SQLException se)
                {
                    Logger.getLogger(addEmployee.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "DataBase error Updation failed!");
                }
            }               
        }
        catch(NumberFormatException Ne)
        {
            JOptionPane.showMessageDialog(this, "Insert correct double value in basic pay!");
        }                                 

    }//GEN-LAST:event_updateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel design;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField empBasic;
    private javax.swing.JTextField empDesign;
    private javax.swing.JTextField empDob;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel header;
    private javax.swing.JLabel id;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pay;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
